app/models/Status.scala, app/models/StatusReason.scala
This was fixed by taking a more hands-on approach when deserialising the incoming JSON packet, rather than relying on the built-in reader system.
A further `StatusReason` type of `EmptyReason` was created to facilitate the result where no status reason was supplied, or that there was no value to convert the status reason into. This allows the reader to then omit the `status_reason` key from the Json object.
=> AMLS-2986: Release 7.1 Defect 239 - failure to post Json data into API 12

app/audit/NotificationReadEvent.scala, app/audit/NotificationReceivedEvent.scala, project/MicroServiceBuild.scala
* Updated platform libraries to latest version
* Modified some audit events according to auditing best practises
=> Platform readiness tweaks

app/audit/NotificationReceivedEvent.scala, app/controllers/NotificationController.scala, app/repositories/NotificationRepository.scala, test/controllers/NotificationControllerSpec.scala
This PR adds more logging and auditing in to try and diagnose a problem with a particular API 12 call, particularly around suspected failing Mongo writes.
=> API 12 logging

project/MicroService.scala, project/MicroServiceBuild.scala, project/plugins.sbt
https://catalogue.tax.service.gov.uk/service/amls-notification
=> Bumped library versions according to service catalogue

conf/application.conf
Updated package version.
Need to be merged only if PR for frontend (branch AMLS-4507) is merged.
**Important:** Once you ready to deploy then change the microservices.services.current-template-package-version in the correct app-config (e.g. app-config-qa) and then re-deploy the last package
=> AMLS-4507 | Changed version in config to v2m0

generate-release-notes.sh
Change release notes gen to prompt for tag
N/A
Local
=> Change release notes gen to prompt for tag

generate-my-release-note.sh, release_notes/AMLS-4893.txt, release_notes/releases/v1.24.0/v1.24.0-21-02-2019.txt
Remove url from release notes
N/A
Local
=> Remove url from release notes

app/controllers/ViewNotificationController.scala, test/connectors/EmailConnectorSpec.scala, test/connectors/ViewNotificationConnectorSpec.scala, test/controllers/NotificationControllerSpec.scala, test/controllers/ViewNotificationControllerSpec.scala
Fixed missing tests (now running 77 out of 77). Only contains changes to unit tests
Passes unit tests
- [] RELEASE NOTES ADDED.
=> AMLS-4738 | FIX: Solved the mystery of the missing tests

app/connectors/DESConnector.scala, app/connectors/EmailConnector.scala, test/connectors/EmailConnectorSpec.scala, test/connectors/ViewNotificationConnectorSpec.scala
Fix failing coverage report in new build. 
N/A
Local + Unit + Coverage
=> Fix failing build

app/audit/ViewNotificationEvent.scala, app/connectors/ViewNotificationConnector.scala, app/utils/AuditHelper.scala, release_notes/AMLS-4945.txt, test/audit/MockAudit.scala, test/connectors/ViewNotificationConnectorSpec.scala
Create audit event for notification read fails. 
N/A
Unit + Regression.
=> Amls 4945 2

release_notes/AMLS-4738.txt, release_notes/releases/v1.34.0/v1.34.0-16-05-2019.txt
Generated deploy release note.
=> Release note after deploy 1.34.0

app/utils/DefaultAuthAction.scala, test/utils/DefaultAuthActionSpec.scala
Turned on test coverage for DefaultAuthAction
- none
- run unit tests, test coverage
=> Amls 5023 - Increase test coverage

conf/application.conf
That's just to test theory tat this switch is causing problems within notification service after Play Upgrade.
- none
- unit test run
=> AMLS-5061 | Turn off auth for ViewNotificationController

app/controllers/ViewNotificationController.scala
Testing why notifications not working after play upgrade
- none
- unit test run
=> AMLS-5061 | authAction to Action.async in ViewNotificationController

app/connectors/DESConnector.scala, app/connectors/EmailConnector.scala, app/connectors/ViewNotificationConnector.scala, app/controllers/ViewNotificationController.scala, conf/application.conf, test/connectors/EmailConnectorSpec.scala, test/connectors/ViewNotificationConnectorSpec.scala, test/controllers/ViewNotificationControllerSpec.scala
Testing new configuration.
- none
- unit tests run
=> AMLS-5061 | Removed references to auth

app/controllers/ViewNotificationController.scala, conf/application.conf
=> AMLS-5061 | Updated configuration

app/controllers/ViewNotificationController.scala, conf/application.conf, project/MicroServiceBuild.scala
=> AMLS-5061 | Changes in config in order to test auth issues

conf/application.conf
As above reverting changes.
- none
- unit tests run
=> Revert "Update application.conf"

app/controllers/ViewNotificationController.scala, conf/application.conf, project/MicroServiceBuild.scala
Reverts hmrc/amls-notification#75
=> Revert "AMLS-5061 | Changes in config in order to test auth issues"

app/controllers/ViewNotificationController.scala, conf/application.conf
Reverts hmrc/amls-notification#74
=> Revert "AMLS-5061 | Updated configuration"

app/controllers/ViewNotificationController.scala, conf/application.conf, test/controllers/ViewNotificationControllerSpec.scala
Reverts hmrc/amls-notification#73
=> Revert "Amls 5061"

app/connectors/DESConnector.scala, app/connectors/EmailConnector.scala, app/connectors/ViewNotificationConnector.scala, app/controllers/ViewNotificationController.scala, conf/application.conf, test/connectors/EmailConnectorSpec.scala, test/connectors/ViewNotificationConnectorSpec.scala, test/controllers/ViewNotificationControllerSpec.scala
Reverts hmrc/amls-notification#72
=> Revert "AMLS-5061 | Removed references to auth"

app/controllers/ViewNotificationController.scala
Reverts hmrc/amls-notification#71
=> Revert "AMLS-5061 | authAction to Action.async in ViewNotificationController"

conf/application.conf
Reverts hmrc/amls-notification#70
=> Revert "AMLS-5061 | Turn off auth for ViewNotificationController"

app/connectors/ViewNotificationConnector.scala
Add HC to DES GET endpoint. 
N/A
Local and Regression Pack
=> Add hc to DES endpoint

app/connectors/DESConnector.scala, app/connectors/ViewNotificationConnector.scala
Second attempt to fix DES header carrier
Regression Pack
=> Second attempt to fix DES header carrier

app/config/ApplicationConfig.scala
=> Removed unnecessary "bearer" in ApplicationConfig

app/connectors/DESConnector.scala, app/connectors/ViewNotificationConnector.scala
Final fix for hc
N/A
Local and Regression
=> Final fix for hc

app/config/ApplicationConfig.scala
=> Removed unnecessary "Env" in ApplicationConfig

app/connectors/EmailConnector.scala, test/connectors/EmailConnectorSpec.scala
=> Email connector end-point update

conf/application.conf
=> AMLS-5734 | Changed notification package versions

conf/application.conf, release_notes/AMLS-5777.txt
=> AMLS-5777 | Updated notifications versions

release_notes/AMLS-5703.txt, release_notes/releases/v1.76.0/v1.76.0-23-03-2020.txt
=> Generated release notes for release 1.76.0

project/MicroServiceBuild.scala, project/build.properties, project/plugins.sbt, release_notes/AMLS-5749.txt
=> Amls 5749 | Updated app dependencies

build.sbt
=> [CU][DLS-3485]: Fix jenkins issue

app/connectors/DESConnector.scala, app/connectors/EmailConnector.scala, app/connectors/ViewNotificationConnector.scala, app/controllers/NotificationController.scala, app/controllers/ViewNotificationController.scala, app/repositories/NotificationRepository.scala, app/utils/DefaultAuthAction.scala, build.sbt, project/AppDependencies.scala, project/plugins.sbt, test/models/fe/NotificationDetailsSpec.scala, test/utils/DefaultAuthActionSpec.scala
=> [CU][DLS-4473]: Play 2.8 upgrades

app/config/ApplicationConfig.scala, app/connectors/EmailConnector.scala, conf/application.conf, test/connectors/EmailConnectorSpec.scala
=> [DLS-4561][Suresh]: use "https" by default when making calls

app/controllers/NotificationController.scala, app/models/NotificationRecord.scala, app/models/NotificationRow.scala, app/models/des/NotificationResponse.scala, app/models/fe/NotificationDetails.scala, app/repositories/NotificationRepository.scala, conf/application.conf, project/AppDependencies.scala, test/controllers/NotificationControllerSpec.scala, test/controllers/ViewNotificationControllerSpec.scala, test/models/NotificationRowSpec.scala, test/models/fe/NotificationDetailsSpec.scala
=> [DLS-5617] Mongo Upgrade Compile

app/repositories/NotificationRepository.scala
=> [DLS-5617] Index Format Fix

project/AppDependencies.scala, project/build.properties, project/plugins.sbt
=> DDCYLS-5409 - dependency upgrades

precheck.sh
=> DDCYLS-6655 - Adding precheck file

app/connectors/DESConnector.scala, app/connectors/EmailConnector.scala, app/connectors/ViewNotificationConnector.scala, conf/application.conf, test/connectors/EmailConnectorSpec.scala, test/connectors/ViewNotificationConnectorSpec.scala
=> DDCYLS-7059 - Upgrade to HttpClientV2
